# @format

blank_issues_enabled: false

contact_links:
  - name: Discussion
    url: https://github.com/resnovas/eventiva/discussions/new?category=general
    about: Start a converstation about our project
  - name: Question & Answers
    url: https://github.com/resnovas/eventiva/discussions/new?category=q-a
    about: Start a converstation about our project
  - name: Get Community Feedback
    url: https://github.com/resnovas/eventiva/discussions/new?category=polls
    about: Ask the community their opinion on something
  - name: Feature Requests
    url: https://github.com/resnovas/eventiva/discussions/new?category=ideas
    about: Open a feature request discussion
  - name: Project Showcase
    url: https://github.com/resnovas/eventiva/discussions/new?category=show-and-tell
    about: Showcase yourself
  - name: Contributor Code of Conduct
    url: https://github.com/Resnovas/eventiva/blob/develop/CODE_OF_CONDUCT.md
    about: Showcase yourself
