name: Documentation review
description: A review to highlight issues in documentation
title: "docs([context]): "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this review, we greatly appriciate it!
  - type: markdown
    attributes:
      value: |
        Please use [context] in title to describe the part of the mono-repo is related to this issue.
        Context example: docs(components): {your title here}
        Valid options are: 
          - directory: The frontend website which displays our directory systems
          - proxy: The api endpoint for proxied connections to private ERP instances
          - image: The build image used when creating private ERP instances 
          - terraform: The definition of our build processes
          - ci/cd: The automations which run at issue create, pull request or push
          - cli: The custom rush based cli, used to streamline development processes
          - erp: The default module within our ERP instances
          - frappe: The frappe ecosystem which our erp instances are built on
          - payments: The payments module within our ERP instances
          - tours: The tours module within our ERP instances
          - logistics: The logistics module within our ERP instances
          - banking: The banking module within our ERP instances
          - tickets: The tickets module within our ERP instances
          - marketing: The marketing module within our ERP instances
          - hospitality: The hospitality module within our ERP instances
  - type: dropdown
    attributes:
      label: Features
      description: What product or feature(s) affected?
      multiple: true
      options:
        - "directory"
        - "proxy"
        - "image"
        - "terraform"
        - "ci/cd"
        - "cli"
        - "erp"
        - "frappe"
        - "payments"
        - "tours"
        - "logistics"
        - "banking"
        - "tickets"
        - "marketing"
        - "hospitality"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Path
      description: What docs or doc section involved? Include links or paths.
      placeholder: "projects/website/readme.md"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Problem
      description: What type of issue have you identified?
      multiple: false
      options:
        - "Problem with a specific document"
        - "Feature/process that's not addressed sufficiently"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Cases
      description: |
        What audience is it intended?
        What roles and scenarios?
        Include use cases, benefits, and/or goals for this work.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solutions
      description: What could we add to make solve this issue? Any concepts, procedures, reference info we could add.
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      description: Where did this first appear (if known) and has any other issues been opened related to this?
      value: |
        Related Pull Request(s):
        Related issue(s):
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/Resnovas/eventiva/blob/develop/CODE_OF_CONDUCT.md)
          required: true
