###
 # Project: @resnovas/eventiva
 # File: cla.yml
 # Path: \.github\workflows\cla.yml
 # Created Date: Saturday, April 15th 2023
 # Author: Jonathan Stevens (jonathan@resnovas.com)
 # -----
 # Last Modified: Sun Apr 16 2023
 # Modified By: Jonathan Stevens
 # Current Version: 0.0.0
 # -----
 # Copyright (c) 2023 Resnovas - All Rights Reserved
 # -----
 # LICENSE: GNU General Public License v3.0 or later (GPL-3.0+)
 # 
 # This program has been provided under confidence of the copyright holder and is 
 # licensed for copying, distribution and modification under the terms of
 # the GNU General Public License v3.0 or later (GPL-3.0+) published as the License,
 # or (at your option) any later version of this license.
 # 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License v3.0 or later for more details.
 # 
 # You should have received a copy of the GNU General Public License v3.0 or later
 # along with this program. If not, please write to: jonathan@resnovas.com ,
 # or see https://www.gnu.org/licenses/gpl-3.0-standalone.html
 # 
 # DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
 # -----
 # HISTORY:
 # Date      	By	Comments
 # ----------	---	---------------------------------------------------------
 ###

# @format

name: Contributor License Agreement Management
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write 
  contents: write
  pull-requests: write
  statuses: write

# Ensures the CLA is signed
jobs:
  CLAssistant:
    name: "CLA Assistant"
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request_target' )
    steps:
      - name: CLA Assistant
        if: ${{env.cla_enabled}} == true
        uses: cla-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          path-to-signatures: "contributors.json"
          path-To-document: "https://github.com/Resnovas/contributors/blob/main/CODE_OF_CONDUCT.md"
          allowlist: ResnovasLtd, dependabot, dependabot[bot], bot*
          branch: "main"
          remote-organization-name: "Resnovas"
          remote-repository-name: "contributors"
